### ISSUE TITLE
Lang files not included in the compiled JS file

### ISSUE THREAD

**Issue by kfay** [YahooArchive/mojito-shaker#13]
Folder structure:

frontend
    mojits
        MyMojit
            lang
                MyMojit.js
            controller.common.js

It appears that the lang file is not included in the compiled JS file, resulting in another JS file downloaded lazily on the client.

**Comment by diervo** [comment]
It was a performance reason behind that (because in Search we have so support many languages), so it was an overhead either in the number of rollups to generate, or in the weight or the file putting all together.

I don't thing should be a must to have the languages rolled up to the client...  Should be lazy-fetched..

Thoughts?

**Comment by kfay** [comment]
Ah ok, I see, that makes sense.  Lazy fetching of the lang files could be ok, but is there any way for them to be fetched from the CDN rather than the FE server?

**Comment by diervo** [comment]
Yes that will be solved when mojito gave us support on the store, which will be on the nex release (after the end of their sprint)
