### ISSUE TITLE
Possible problems with lang-files

### ISSUE THREAD

**Issue by ItsAsbreuk** [YahooArchive/mojito-shaker#52]
Inside Mojito's application.json, I have a custom yui-configuration for the client.
The app runs well.

After running/using shaker it seems that the custom comboloader (on the client) tries to load:

```
yui3/3.11.0/build/calendar/lang/calendar_nl.js
```

instead of

```
yui3/3.11.0/build/calendar-base/lang/calendar_nl.js
```

I can't figure out where things go wrong, but I can see that the misspelled url only is there when shaker is active. Hope this makes sense.

Marco.

**Comment by caridy** [comment]
@ItsAsbreuk it is either:

```
yui3/3.11.0/build/calendar-base/lang/calendar-base_nl.js
```

notice that the name of the folder is always the same as the filename, in this case `calendar-base`.

I don't think this problem has anything to do with shaker though.

**Comment by ItsAsbreuk** [comment]
Hi Caridy.

1) you are right about yui3/3.11.0/build/calendar-base/lang/calendar-base_nl.js in a good working environment. That was a typo indeed.

2) Sorry, but the error does exist and is due to Shaker. I tested it by making a new empty Mojitoproject using YUI on the cdn. To show what I meant, I can give you the following info:
- netstats when running app without shaker (no error): http://projects.itsasbreuk.nl/test-examples/language-working.png
- netstats when running shaker (with error): http://projects.itsasbreuk.nl/test-examples/language-error400.png
- netstats-detailed when running shaker (with detailed error): http://projects.itsasbreuk.nl/test-examples/language-error.png
- used application.json and Home-mojit files: https://gist.github.com/ItsAsbreuk/18c449a00b30c27752ac

The strange thing here is, that in both cases a custom client-YUI config is running on the client. But when shaked it seems to call 'calendar/lang/calendar_nl.js' which does not exist (as shown in 'netstats-detailed').

Marco.

**Comment by aljimenez** [comment]
Hi Marco,

Thanks for your detailed explanation of the issue you found. I was able to reproduce the error and it seems like the issue is not related to lang files. Instead the issue arises from conflicting YUI versions. The yui configuration in application.json is different from what is used by Mojito. When generating rollups, Shaker gets the YUI core files from the shallowest YUI package. So if the app does not require its own YUI package, Shaker uses the one used by Mojito. As a results your rollups end up using a different version of YUI, in this case 3.10.3 instead of 3.13.0-rc-1. One solution is to set shaker->resources->yui to false. This ensures that rollups do not contain the core YUI files. Another solution is to make your application require the YUI version that you specify in application.json. This way Shaker generates the rollups using the expected YUI core files. Try using the latest version of Shaker.

Albert

**Comment by ItsAsbreuk** [comment]
Hi Albert,

Thanks for your reply.

I managed to disable resources yui. The biggest drawback is now that Shaker's functionality is almost gone: this leads to many requests (url-length limited) from my own comboloader.

The best solution would be your second advise: but I don't see any means how I can make Mojito run at the server-side with another YUI-version (and comboloader) than that is used within the specific Mojito-version. Is this possible at all?

btw I ran shaker-4.0.27 but upgraded to shaker-4.0.29 now.
Hope you can build this feature (using custimized yui-app versions) in a next shaker-version.

Kind Regards,
Marco

**Comment by aljimenez** [comment]
Hi Marco,

The current mojito list yui as ("yui": "~3.10.0") in its package.json. Lets say you would like to use yui@3.13.x, then you can list yui as ("yui": "3.13.x") in your app's package.json. During compilation, Shaker will see that your app has its own yui dependency so it will use it instead of mojito's yui dependency when building rollups. This means that your rollup will include core yui modules such as yui-base and loader-base at version 3.13.x. I hope this works for you.

Something else I've been thinking about doing is allowing users to specify specific paths of yui modules through the configuration such as resources->yui->calendar->"http://some_site.com/calendar.js" or resources->yui->calendar->"./myModules/calendar.js". If you have any feedback, we would love to hear about it.

Thanks,
Albert

**Comment by caridy** [comment]
Even though this is doable doesn't necessary means that it is going to work. If mojito doesn't use the proper yui version, the metadata generated for the app (dependencies and stuff) might fail to fulfill your needs. In other words, try to avoid this situation as much as possible.

**Comment by ItsAsbreuk** [comment]
HI Albert and Caridy,

Sorry for the late response (due to a lot of work here)

I use a custom comboloader, due to customized modules and ssl-support. Even if this comboloader isn't called once shaked, there might be situations that shaker is turned of -temporarely- or when I need to set "bootstrap: false" as mentioned in https://github.com/yahoo/mojito-shaker/issues/45#issuecomment-18457439

I think best way is to keep stick to the same YUI-version. This solves the problem and seems to me a wise advise to follow.

Personally, I wouldn't use specific paths for seperate modules. Like said, I setup an own comboloader that serves specific YUI3-versions, some gallery-versions and custom private modules that I didn't put in the gallery. Being able to specify base-paths suffice.

Kind regards,
Marco
