### ISSUE TITLE
Few CSS/JS issues

### ISSUE THREAD

**Issue by Sai4anand** [YahooArchive/mojito-shaker#6]
I found following issues in mojito-shaker:
1.  Cyclic dependency of assets has not been handled. It gives buffer overflow error.
2. filter:alpha(opacity = 40);  gives error if there is a space before and after '='  whereas it works fine if there is no space.
3. JSlint doesn't throw error if minification of JS fails.

**Comment by twobit** [comment]
More issues reported by Sai4anand:

After installation when I run shaker, it gives “isArray is not a method” error. I removed this by replacing it with “instanceof array”. Also it gives checksum null error  for which I had to put that method call into try-catch. We cannot do this in the production. When will the fix for these issues be available.

Currently, shaker does rollup for all the mojits in mojits directory and not the page level rollup based on the config in application.json. Currently we have 3 pages(may increase later), with each page having different set of mojits. Rolling up them together increases the size of static assets and affects page performance.

Also whenever we run the shaker, it does rollup for static assets even if there is no modification in the assets.

After running the shaker in prod/test env, when I restart the server, the JS files are not served from the rolled up directory/mobster although CSS works fine(may be I am missing something in config). Can you please let me know if something needs to be done to avoid the same.

Cyclic dependency issue raised here:
/yahoo/mojito-shaker/issues/8

**Comment by twobit** [comment]
These issues have been addressed and or fixed. Please verify.
